version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
    angular-service: # The name of the service
      container_name: angularcontainer  # Container name
      build: ./angulardockerproject # Location of our Dockerfile
      volumes: # Volume binding
        - './angulardockerproject:/usr/src/app1' 
      ports: 
        - '4200:4200' # Port mapping
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    ms-sql-server: 
      image: "microsoft/mssql-server-linux:latest"
      environment: 
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "MyPass@word"
        MSSQL_PID: "Express"
      ports:
        - "1433:1433"
    colour-api:
        build: ./colourapi
        ports: 
          - "8080:80"